name: Generate Meta Catalog and Rebuild Hugo Site

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-and-rebuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML GitPython python-slugify

    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Generate Meta Catalog
      run: python src/capture_knowledge/generate_meta_catalog.py

    - name: Build Hugo site
      run: hugo --minify

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update meta catalog and rebuild site" || echo "No changes to commit"
        git push